---
version: "2"
services:
  signal_bot:
    restart: unless-stopped
    build: "."
    container_name: signal_bot
    volumes:
      - /var/run/signald:/var/run/signald
      - /mnt/store/signal_archive_bot:/store
    env_file:
      - config.env
